### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by shang766** [pengyuzhang97/Muti-view-Action-Recognition#1]
您好！很感谢您可以分享代码！目前IXMAS数据集下载链接都失效了，如果可以的话，可以分享一下5个cameras.avi嘛？谢谢！

**Comment by pengyuzhang97** [comment]
你好，数据集链接如下：https://www.epfl.ch/labs/cvlab/data/data-ixmas10/


> 您好！很感谢您可以分享代码！目前IXMAS数据集下载链接都失效了，如果可以的话，可以分享一下5个cameras.avi嘛？谢谢！

**Comment by shang766** [comment]
非常感谢！
